<?php
$sty = '<style>
  body{font-family: sans-serif; font-size: 12px; color:#111;}
  h1{font-size:20px;margin:0 0 6px 0;}
  h2{font-size:14px;margin:12px 0 6px 0;border-bottom:1px solid #ddd;padding-bottom:4px;}
  .grid{display:flex;flex-wrap:wrap}
  .col{width:50%;box-sizing:border-box;padding:4px 8px}
  .row{margin-bottom:6px}
  .box{border:1px solid #ddd;border-radius:6px;padding:8px;margin-bottom:10px}
  .meta{font-size:11px;color:#444}
  .photos img{height:140px;margin:4px;border:1px solid #ccc;padding:2px;border-radius:4px}
  .muted{color:#666}
</style>';
echo $sty;
?>
<table width="100%" cellpadding="0" cellspacing="0">
  <tr>
    <td><h1>Clean-Up Notice #<?php echo (int)$data['id']; ?></h1>
      <div class="meta">Generated on <?php echo date('Y-m-d H:i'); ?></div>
    </td>
    <td align="right">
      <?php if(file_exists($data['logo_path'])): ?>
        <img src="<?php echo $data['logo_path']; ?>" height="48">
      <?php endif; ?>
    </td>
  </tr>
</table>
<div class="box">
  <div class="grid">
    <div class="col"><strong>Site Name:</strong> <?php echo esc($data['site_name']); ?></div>
    <div class="col"><strong>Contract No:</strong> <?php echo esc($data['contract_no']); ?></div>
    <div class="col"><strong>Location:</strong> <?php echo esc($data['location']); ?></div>
    <div class="col"><strong>Issued At:</strong> <?php echo esc($data['issued_at']); ?></div>
    <div class="col"><strong>Issued To:</strong> <?php echo esc($data['issued_to']); ?></div>
    <div class="col"><strong>Issued By:</strong> <?php echo esc($data['issued_by']); ?></div>
  </div>
</div>
<div class="box">
  <h2>Reason for Notification</h2>
  <div class="row"><?php echo nl2br(esc($data['reason'])); ?></div>
</div>
<div class="box">
  <h2>Notice Details</h2>
  <div class="row"><strong>Description:</strong><br><?php echo nl2br(esc($data['description'])); ?></div>
  <div class="row"><strong>Urgency:</strong> <?php echo esc($data['urgency']); ?><?php if($data['deadline_at']) echo ' — Deadline: ' . esc($data['deadline_at']); ?></div>
  <div class="row"><strong>Outcome:</strong>
    <?php
      $out = [];
      if($data['completed_ok']) $out[] = 'Completed OK: ' . esc($data['completed_ok']);
      if($data['mcgoff_clear']) $out[] = 'McGoff to clear: ' . esc($data['mcgoff_clear']);
      echo esc(implode(' | ', $out));
    ?>
  </div>
</div>
<div class="box">
  <h2>Photos</h2>
  <div class="photos">
  <?php if(!empty($data['photo_paths'])): ?>
    <?php foreach($data['photo_paths'] as $p): if(file_exists($p)): ?>
      <img src="<?php echo $p; ?>">
    <?php endif; endforeach; ?>
  <?php else: ?>
    <div class="muted">No photos provided.</div>
  <?php endif; ?>
  </div>
</div>
<div class="box">
  <h2>Signature</h2>
  <?php if(!empty($data['signature_path']) && file_exists($data['signature_path'])): ?>
    <img src="<?php echo $data['signature_path']; ?>" height="120">
  <?php else: ?>
    <div class="muted">No signature captured.</div>
  <?php endif; ?>
</div>
<div class="meta">This document was generated by Defect Tracker.</div>
